### ISSUE TITLE
Scope for handlebar snippets

### ISSUE THREAD

**Issue by offirgolan** [terminalvelocity/ember-cli-sublime-snippets#6]
Can you add the following to the handlebars snippets? That way it wont show up in JS files

```
<scope>text.html.handlebars</scope>
```

**Comment by offirgolan** [comment]
Thank you! 😁

**Comment by jhliberty** [comment]
Thanks for opening an issue! 

![giphy](https://cloud.githubusercontent.com/assets/449321/12402166/c1574868-bdf0-11e5-9ecd-1d125c2392db.gif)
